"""`story-automator setup` — bootstrap the automator into a BMAD project.

A fresh BMAD install ships the standard `bmad-*` skills but NOT the automator's
review bridge, and never writes the per-project `story-automator.yaml`. This
command stamps both into a target project so the global story-automator skill
can run there, and verifies the Stop hook + marker gitignore.

Idempotent: existing files are left untouched unless `--force` is passed. Prints
a human summary by default, or a machine payload with `--json`.
"""

from __future__ import annotations

import contextlib
import io
import json
import shutil
from pathlib import Path

from ..core.utils import ensure_dir, file_exists, read_text, run_cmd, write_atomic
from .basic import cmd_ensure_marker_gitignore, cmd_ensure_stop_hook

BRIDGE_SKILL = "bmad-story-automator-review"


def _workflow_root() -> Path:
    # <skill_root>/src/story_automator/commands/setup.py -> <skill_root>
    return Path(__file__).resolve().parents[3]


def _template_scaffold() -> Path:
    return _workflow_root() / "templates" / "project-scaffold"


def _resolve_project_root(args: list[str]) -> Path:
    for idx, arg in enumerate(args):
        if arg in ("--project-root", "-C") and idx + 1 < len(args):
            return Path(args[idx + 1]).expanduser().resolve()
    positional = [a for a in args if not a.startswith("-")]
    if positional:
        return Path(positional[0]).expanduser().resolve()
    cwd = Path.cwd()
    result = run_cmd("git", "-C", str(cwd), "rev-parse", "--show-toplevel")
    if result.exit_code == 0 and result.output.strip():
        return Path(result.output.strip()).resolve()
    return cwd.resolve()


def _bmad_project_name(root: Path) -> str:
    """Read project_name from BMAD's config, falling back to the dir name."""
    for rel in ("_bmad/bmm/config.yaml", "_bmad/automator/config.yaml", "_bmad/core/config.yaml"):
        path = root / rel
        if not path.is_file():
            continue
        try:
            text = read_text(path)
        except OSError:
            continue
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("project_name:"):
                value = stripped.split(":", 1)[1].strip().strip("'\"")
                if value:
                    return value
    return root.name


def _detect_test_gauntlet(root: Path) -> list[str]:
    """Best-effort test commands based on stack markers at the project root.

    Returns an empty list for stacks we can't detect — the automate step then
    runs with no gate, which is correct for early-stage projects.
    """
    if (root / "package.json").is_file():
        try:
            pkg = json.loads(read_text(root / "package.json"))
        except (OSError, ValueError):
            pkg = {}
        scripts = pkg.get("scripts") or {}
        cmds = [f"npm run {name}" for name in ("lint", "test", "build") if name in scripts]
        if "test" in scripts and "npm run test" in cmds:
            cmds[cmds.index("npm run test")] = "npm test"
        return cmds
    if (root / "Cargo.toml").is_file():
        return ["cargo fmt --check", "cargo clippy -- -D warnings", "cargo test"]
    if (root / "go.mod").is_file():
        return ["go vet ./...", "go test ./..."]
    if (root / "pyproject.toml").is_file() or (root / "setup.py").is_file():
        return ["python -m pytest"]
    return []


def _render_yaml(project_name: str, gauntlet: list[str]) -> str:
    if gauntlet:
        gauntlet_block = "test_gauntlet:\n" + "".join(f"  - {cmd}\n" for cmd in gauntlet)
    else:
        gauntlet_block = (
            "test_gauntlet: []\n"
            "#   - cd app && npm ci && npm run lint && npm test && npm run build\n"
        )
    return (
        "# story-automator per-project config.\n"
        "# All keys are OPTIONAL — safe defaults apply if this file (or any key)\n"
        "# is absent. Generated by `story-automator setup`; edit freely.\n"
        "\n"
        "# Display name — tmux session prefix + branch slug.\n"
        f"project_name: {project_name}\n"
        "\n"
        "# Shell commands the `automate` step must ALL pass (from project root)\n"
        "# before review runs. Empty = no gate.\n"
        f"{gauntlet_block}"
        "\n"
        "reviewer:\n"
        "  # Review-bridge skill the review step invokes (must exist under\n"
        "  # .claude/skills/). Installed by this setup command.\n"
        f"  bridge: {BRIDGE_SKILL}\n"
        "  # Optional senior-reviewer skills the bridge dispatches to. Omit to\n"
        "  # use the bridge's built-in adversarial review.\n"
        "  # backend: bmad-code-review\n"
        "  # frontend: bmad-code-review\n"
        "\n"
        "# PR / branch behaviour. Default branch is epic<N>/<story-slug> off main.\n"
        'branch_pattern: "epic{epic}/{story_slug}"\n'
        "open_pr: true\n"
        "copilot_loop: true\n"
    )


def _copy_bridge(root: Path, force: bool) -> dict[str, object]:
    src = _template_scaffold() / "skills" / BRIDGE_SKILL
    dst = root / ".claude" / "skills" / BRIDGE_SKILL
    if not src.is_dir():
        return {"item": "review-bridge", "status": "error", "detail": f"template missing: {src}"}
    if dst.exists() and not force:
        return {"item": "review-bridge", "status": "skipped", "detail": f"exists: {dst}"}
    ensure_dir(dst.parent)
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)
    return {"item": "review-bridge", "status": "forced" if force else "created", "detail": str(dst)}


def _write_yaml(root: Path, force: bool) -> dict[str, object]:
    dst = root / "_bmad" / "automator" / "story-automator.yaml"
    if dst.is_file() and not force:
        return {"item": "story-automator.yaml", "status": "skipped", "detail": f"exists: {dst}"}
    project_name = _bmad_project_name(root)
    gauntlet = _detect_test_gauntlet(root)
    ensure_dir(dst.parent)
    write_atomic(dst, _render_yaml(project_name, gauntlet))
    detail = f"{dst} (project_name={project_name}, test_gauntlet={len(gauntlet)} cmds)"
    return {"item": "story-automator.yaml", "status": "forced" if force else "created", "detail": detail}


def _quiet(fn, argv: list[str]) -> int:
    # The reused ensure_* helpers write their own JSON to stdout; swallow it so
    # this command owns its output (clean --json, tidy human summary).
    with contextlib.redirect_stdout(io.StringIO()):
        return fn(argv)


def _ensure_hook(root: Path) -> dict[str, object]:
    settings = root / ".claude" / "settings.json"
    # Reuse the audited ensure logic; it resolves the command to the global
    # script path and normalises an existing hook in place.
    rc = _quiet(cmd_ensure_stop_hook, ["--settings", str(settings), "--command", "story-automator stop-hook"])
    return {"item": "stop-hook", "status": "ok" if rc == 0 else "error", "detail": str(settings)}


def _ensure_gitignore(root: Path) -> dict[str, object]:
    gitignore = root / ".gitignore"
    rc = _quiet(
        cmd_ensure_marker_gitignore,
        ["--gitignore", str(gitignore), "--entry", ".claude/.story-automator-active"],
    )
    return {"item": "marker-gitignore", "status": "ok" if rc == 0 else "error", "detail": str(gitignore)}


def cmd_setup(args: list[str]) -> int:
    if args and args[0] in ("--help", "-h"):
        print("Usage: story-automator setup [PROJECT_ROOT] [--force] [--json]")
        print("  Bootstraps the review bridge + story-automator.yaml + Stop hook.")
        print("  PROJECT_ROOT defaults to the git toplevel of the current directory.")
        return 0

    force = "--force" in args
    as_json = "--json" in args
    root = _resolve_project_root([a for a in args if a not in ("--force", "--json")])

    if not (root / "_bmad").is_dir():
        payload = {"ok": False, "error": "not_a_bmad_project", "projectRoot": str(root)}
        print(json.dumps(payload, indent=2) if as_json else f"✗ {root} has no _bmad/ — is this a BMAD project?")
        return 1

    results = [
        _copy_bridge(root, force),
        _write_yaml(root, force),
        _ensure_hook(root),
        _ensure_gitignore(root),
    ]
    ok = all(r["status"] != "error" for r in results)
    payload = {"ok": ok, "projectRoot": str(root), "actions": results}

    if as_json:
        print(json.dumps(payload, indent=2))
        return 0 if ok else 1

    print(f"story-automator setup — {root}")
    marks = {"created": "✓", "forced": "✓", "ok": "✓", "skipped": "•", "error": "✗"}
    for r in results:
        print(f"  {marks.get(str(r['status']), '?')} {r['item']}: {r['status']} — {r['detail']}")
    if ok:
        print("\nReady. Run the automator from this project root (\"run story automator\").")
    else:
        print("\nSome steps failed — see above.")
    return 0 if ok else 1
